const $=s=>document.querySelector(s),DAYS=['Воскресенье','Понедельник','Вторник','Среда','Четверг','Пятница','Суббота'],TIMES={1:'09:30–11:00',2:'11:10–12:40',3:'13:00–14:30',4:'15:10–16:40',5:'17:00–18:30',6:'18:40–20:10'};
const savedSubgroup=localStorage.getItem('guap-subgroup');
let schedule=structuredClone(DEFAULT_SCHEDULE),editingId=null,currentWeek='blue',subgroup=savedSubgroup===null?NaN:Number(savedSubgroup);
const cloudReady=Boolean(APP_CONFIG.supabaseUrl&&APP_CONFIG.supabaseAnonKey);
const formatDate=d=>d.toLocaleDateString('ru-RU',{day:'numeric',month:'long'}),uid=()=>crypto.randomUUID();
function mondayOf(d){d=new Date(d);d.setHours(0,0,0,0);d.setDate(d.getDate()-((d.getDay()+6)%7));return d}function weekFor(date){const x=Math.round((mondayOf(date)-mondayOf(new Date()))/604800000);return((x%2===0)===(currentWeek==='blue'))?1:2}
function showStart(){const known=[0,1,2].includes(subgroup);$('#subgroupPrompt').classList.toggle('hidden',known);$('#scheduleView').classList.toggle('hidden',!known);if(known)render()}
function card(x){const b=x.subgroup?`<span class="subgroup s${x.subgroup}">подгруппа ${x.subgroup}</span>`:'';return `<article class="lesson"><div class="lesson-time"><b>${x.pair} пара</b><span>${TIMES[x.pair]}</span></div><div class="lesson-body">${b}<p class="lesson-type">${x.type}</p><h2>${x.title}</h2><p>📍 ауд. ${x.room}, Б. Морская 67</p><p>👨‍🏫 ${x.teacher}</p></div></article>`}
function render(){const start=new Date();start.setHours(0,0,0,0);$('#lessons').innerHTML=Array.from({length:14},(_,i)=>{const date=new Date(start);date.setDate(start.getDate()+i);const day=date.getDay(),week=weekFor(date),items=day===0?[]:schedule.filter(x=>x.day===day&&(x.subgroup===0||subgroup===0||x.subgroup===subgroup)&&((x.week||0)===0||(x.week||0)===week)).sort((a,b)=>a.pair-b.pair);return `<section class="schedule-day"><div class="day-heading"><div><h2>${i===0?'Сегодня · ':''}${DAYS[day]}</h2><p>${formatDate(date)}</p></div><span class="week-badge ${week===1?'blue-week':'red-week'}">${week===1?'синяя':'красная'} неделя</span></div>${items.length?items.map(card).join(''):'<div class="empty compact"><span>🌤️</span><p>Занятий нет</p></div>'}</section>`}).join('')}
async function loadCloud(){if(!cloudReady)return;try{const response=await fetch(`${APP_CONFIG.supabaseUrl}/rest/v1/app_data?id=eq.schedule&select=value`,{headers:{apikey:APP_CONFIG.supabaseAnonKey,Authorization:`Bearer ${APP_CONFIG.supabaseAnonKey}`}});const data=await response.json(),value=data?.[0]?.value;if(value?.version===2){if(value.lessons?.length)schedule=value.lessons;if(value.currentWeek)currentWeek=value.currentWeek;render()}}catch(_){/* Встроенное расписание продолжает работать без облака. */}}
async function adminRequest(action,extra={}){if(!cloudReady)throw new Error('Сначала подключите Supabase в config.js.');const initData=window.Telegram?.WebApp?.initData;if(!initData)throw new Error('Откройте приложение внутри Telegram.');const response=await fetch(`${APP_CONFIG.supabaseUrl}/functions/v1/admin-schedule`,{method:'POST',headers:{'Content-Type':'application/json','apikey':APP_CONFIG.supabaseAnonKey},body:JSON.stringify({action,initData,...extra})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Нет доступа.');return result}
async function saveCloud(){try{await adminRequest('save',{schedule,currentWeek,version:2});render();return true}catch(error){alert(error.message);return false}}
function renderEditor(){$('#weekSetting').value=currentWeek;$('#adminLessons').innerHTML=[...schedule].sort((a,b)=>a.day-b.day||a.pair-b.pair).map(x=>`<button class="admin-item" data-id="${x.id}"><b>${DAYS[x.day]} · ${x.pair} пара</b><span>${x.title}${x.subgroup?' · п/г '+x.subgroup:''}${x.week?' · '+(x.week===1?'синяя':'красная')+' неделя':''}</span></button>`).join('')}
async function openAdmin(){$('#adminDialog').showModal();$('#loginBox').classList.remove('hidden');$('#editorBox').classList.add('hidden');try{await adminRequest('check');$('#loginBox').classList.add('hidden');$('#editorBox').classList.remove('hidden');renderEditor()}catch(error){$('#loginBox').innerHTML=`<p>${error.message}</p>`}}
function openEdit(item){editingId=item?.id||null;const f=$('#lessonForm');f.reset();if(item)Object.entries(item).forEach(([k,v])=>f.elements[k]&&(f.elements[k].value=v));$('#lessonDialogTitle').textContent=item?'Изменить занятие':'Новое занятие';$('#deleteLesson').classList.toggle('hidden',!item);$('#lessonDialog').showModal()}
document.querySelectorAll('[data-subgroup]').forEach(b=>b.onclick=()=>{subgroup=Number(b.dataset.subgroup);localStorage.setItem('guap-subgroup',subgroup);showStart()});$('#adminOpen').onclick=openAdmin;document.querySelectorAll('.close-dialog').forEach(x=>x.onclick=()=>$('#adminDialog').close());$('.close-lesson').onclick=()=>$('#lessonDialog').close();
$('#saveWeek').onclick=async()=>{currentWeek=$('#weekSetting').value;if(await saveCloud())renderEditor()};$('#addLesson').onclick=()=>openEdit();$('#logout').onclick=()=>$('#adminDialog').close();$('#adminLessons').onclick=e=>{const b=e.target.closest('[data-id]');if(b)openEdit(schedule.find(x=>x.id===b.dataset.id))};
$('#lessonForm').onsubmit=async e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));['day','pair','subgroup','week'].forEach(k=>o[k]=Number(o[k]));o.id=editingId||uid();const n=schedule.findIndex(x=>x.id===o.id);if(n<0)schedule.push(o);else schedule[n]=o;if(await saveCloud()){$('#lessonDialog').close();renderEditor()}};$('#deleteLesson').onclick=async()=>{if(!editingId||!confirm('Удалить это занятие?'))return;schedule=schedule.filter(x=>x.id!==editingId);if(await saveCloud()){$('#lessonDialog').close();renderEditor()}};
if(window.Telegram?.WebApp){Telegram.WebApp.ready();Telegram.WebApp.expand();Telegram.WebApp.setHeaderColor('#0f5bd7')}showStart();loadCloud();
